#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Logic/ChessData.h"
#include "ChessPieceActor.generated.h"

UCLASS(Blueprintable)
class CHESSGAME_API AChessPieceActor : public AActor
{
	GENERATED_BODY()
	
public:	
	AChessPieceActor();

	UPROPERTY(BlueprintReadWrite, VisibleAnywhere)
	int32 PieceId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EPieceType Type;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EPieceColor Color;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Chess")
	TSubclassOf<class AChessMoveRule> MoveRuleClass;

	UPROPERTY(BlueprintReadWrite, Category = "Chess")
	class AChessMoveRule* MoveRuleInstance;

	// Cache valid moves for this piece (generated by the rule)
	UPROPERTY(BlueprintReadWrite)
	TArray<FChessMove> CachedMoves;

	UFUNCTION(BlueprintCallable)
	void UpdateLegalMoves(const UChessBoardState* Board);

	UFUNCTION(BlueprintImplementableEvent)
	void OnInitialized(int32 InPieceId, EPieceType InType, EPieceColor InColor);

	UFUNCTION(BlueprintImplementableEvent)
	void OnMoved(FBoardCoord From, FBoardCoord To, ESpecialMoveType MoveType);

	UFUNCTION(BlueprintImplementableEvent)
	void OnCaptured();

	UFUNCTION(BlueprintImplementableEvent)
	void OnPromoted(EPieceType NewType);

public:
	void Init(int32 InPieceId, EPieceType InType, EPieceColor InColor);

};
